### ISSUE TITLE
SI units?

### ISSUE THREAD

**Issue by lassefolkersen** [andrewkern/bagels#4]
Is it possible to provide these algorithms in SI units? I had some trouble following the whole "oz" and "cup" system. It would wonders for code portability.

**Comment by andrewkern** [comment]
yes definitely-- i can convert my recipe to grams easily enough

**Comment by andrewkern** [comment]
okay @lassefolkersen i think i now have everything in SI units as of #5. would you mind taking a look to see if this is easy enough to follow where you are?

**Comment by lassefolkersen** [comment]
Yes, it looks good in code review, but I haven't had time to production test it yet. Thanks!

**Comment by andrewkern** [comment]
okay! i'll close this for now but feel free to reopen
